# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hkSMv5WOrm5ACchpfIXf6OqHTW3zPxhl
"""

import pandas as pd
prices=[2999,15999,2000,5999,9999]
products=['wireless earbuds','mobile','Watch','bluetooth','smartphone']
product_prices=pd.Series(prices,index=products)
print(product_prices)

print("Mean",product_prices.mean())
print("Median",product_prices.median())
print("Standard Deviation",product_prices.std())
print("Maximum",product_prices.max())
print("Minimum",product_prices.min())
print("Sum",product_prices.sum())

print(product_prices.head(3))
print(product_prices.tail(2))

print(product_prices.apply(lambda x: f'₹{x+(x*0.18)}'))
print(product_prices.map(lambda x: f'₹{x}.00'))

print(product_prices.sort_values(ascending=False))
print(product_prices.sort_index())
print(product_prices.sort_index(ascending=False))
print(product_prices.value_counts())

data={
    "product":["wireless earbuds","smartphone","mobile","Watch","bluetooth"],
    "price":[2999,15999,2000,5999,9999],
    "stock":[10,20,30,40,50],
    "brand":['vivo','samsung','motorala','realme','apple'],
    "bestseller":[True,False,True,True,False]
}
df=pd.DataFrame(data)
print(df)

from google.colab import files
import pandas as pd
uploaded=files.upload()
df=pd.read_excel("dataset.xlsx")
print(df)

print(df.shape)
print(df.columns)
print(df.info())

print(df.head(10))
print(df.tail(9))

print(df.iloc[0])
print(df.iloc[1])
print(df.iloc[2])
print(df['Product'])

print(df)
print(df.loc[2,"Brand"])
print(df.loc[3,"Product"])
print(df.loc[4,"Price"])
print(df.loc[5,"Stock"])
print(df.loc[6,"Brand"])
print(df.iloc[4,0])
print(df.iloc[2,1])
print(df.iloc[3,2])
print(df.iloc[5,3])
print(df.iloc[6,4])

df_dropped=df.drop(columns=["Stock"])
print("After Dropping")
print(df_dropped)

df_renamed=df.rename(columns={"Product":"Products"})
print("After Renaming")
print(df_renamed)

print(df)
print("bestseller true")
print(df.loc[df['BestSeller']==True])
print("stock is less than 40")
print(df.loc[df['Stock']<40])
print("price is less than 10000")
print(df.loc[df['Price']<10000])

df_grouped=df.groupby("Brand").agg({"Price":"mean", "Stock":"sum"})
print(df_grouped)
grouped=df.groupby("Brand").agg({"Price":["mean","max","sum","min"]})
print(grouped)
grouped=df.groupby("Brand")["Price"].mean()
print(grouped)

data2={
    "Brand":["vivo","samsung","motorala","realme","apple"],
    "Product":["wireless earbuds","smartphone","mobile","Watch","bluetooth"],
    "Price":[2999,15999,2000,5999,9999],
    "Stock":[10,20,30,40,50]

}
df_price=pd.DataFrame(data2)
print(df_price)
df_price_stock=pd.merge(df,df,on="Price")
print(df_price_stock)
print("After Merging")
df_merged=pd.merge(df,df_price,on="Brand")
print(df_merged)

new_data={
    "Brand":["Tablet"],
    "Product":["wireless phone"],
    "Price":[2999],
    "Stock":[10],
    "BestSeller":[True]
}
df_new=pd.DataFrame(new_data)
print(df_new)

df_concat=pd.concat([df,df_new])
print(df_concat)