# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lWcc2iFXvJgmvb5lFD4JOu1yedECXpVw
"""

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print("1-dim",arr1,sep='\n',end='\n\n')
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2-dim",arr2,sep='\n',end='\n\n')
arr3 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print("multi-dim",arr3,sep='\n')

zeros = np.zeros((4,4))
print(zeros)
ones = np.ones((2, 2))
print(ones)
identity = np.eye(4)
print(identity)
full_array = np.full((10, 2),"sloted")
print(full_array)

np.random.seed(40)
rand_arr = np.random.randint(100)
print(rand_arr)
rand_int = np.random.randint(30,60)
print(rand_int)
rand_int = np.random.randint(1, 6, 20)
print(rand_int)
rand_int = np.random.randint(1, 6, (4, 5))
print(rand_int)

rand_float = np.random.rand(10)
print(rand_float)
rand_float = np.random.rand()
print(rand_float)

lang=['html','css','javascript','python','mysql']
rand_choice = np.random.choice(lang, 3)
print(rand_choice)

arr = np.array([[1, 2], [4, 5],[6,7],[8,7],[1,2],[4,5]])
print(arr.shape)
reshaped = arr.reshape(4,3)
print(reshaped)
flattened = arr.flatten()
print(flattened)
transposed = arr.T
print(transposed)

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(matrix[0:3, 0])
print(matrix[0:3, 1])
print(matrix[0:2, 0:2])
print(matrix[1:3,1:3])

arr = np.array([4, 9, 16, 25, 36])

print(arr+10)
print(arr*2)
print(arr**0.5)
print(arr%2==0)
print(arr[arr%2!=0])

a = np.array([1, 2, 3, 4, 5])

print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.median(arr))
print(np.mean(a))
print(np.var(a))
print(np.std(a))
print(np.sort(arr))

arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

unique_vals = np.unique(arr)
print(unique_vals)

split_arr = np.split(np.array([1, 2, 3, 4, 5, 6]), 3)
print(split_arr)

arr = np.array([10, 20, 30])
view_arr = arr.view()
view_arr[0] = 100
print(arr,view_arr)

copy_arr = arr.copy()
copy_arr[0] = 200
print(arr,copy_arr)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))

print(np.linalg.det(A))

print(np.linalg.inv(A))

eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)

print(eigenvectors)

C = np.array([5, 11])
solution = np.linalg.solve(A, C)
print(solution)