# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVAsA8TU5DEGRVmK_FW4mNczYf6Rrryh
"""

import matplotlib.pyplot as plt
hours=[1,2,3,4,5,6,7,8]
visitors=[50,60,75,80,96,100,110,115]

plt.plot(hours,visitors,
         color="green",
         marker="o",
         linestyle="--",
         linewidth=2,
         alpha=1,
         label="visitors")

plt.title("Visitors per hour")
plt.xlabel("Hours")
plt.ylabel("Visitors")
plt.legend()
plt.grid(True, linestyle="--", alpha=1)
plt.show()

import matplotlib.pyplot as plt
product=["laptop","mobiles","Tablet","headphone","smartwatch"]
sales=[250,400,150,300,500]
plt.bar(product,sales,color="yellow",edgecolor='black',alpha=1,width=0.5)
plt.title("product sales camparsion")
plt.xlabel("products")
plt.ylabel("units sold")
plt.show()

import matplotlib.pyplot as plt
marks=[90,100,45,89,66,45,89,98,92,
       19,54,96,81,80,72,65,34,65,87,
       88, 87,86,87,98,83,25,34,12,21]
plt.hist(marks,bins=,histtype='bar',color="orange",edgecolor="black",density=True)
plt.title("marks distribution")
plt.xlabel("marks")
plt.ylabel("frequency")
plt.show()

import matplotlib.pyplot as plt
brands=["apple","samsung","vivo","motorola","lenovo","lava"]
market_share=[30,25,20,5,15,46]
plt.pie(market_share,
        labels=brands,
        autopct="%.2f%%",
        startangle=90,
        colors=["orange","blue","green","purple","red","yellow"],
        explode=[0,0,0,0.1,0,0],
        shadow=True)
plt.title("mobile market share")
plt.show()

import matplotlib.pyplot as plt
ad_spend=[2,4,6,8,10,12,45,67]
profit=[20,56,75,64,45,98,10,98]
colors=[8,1,2,3,5,6,7,9]
plt.scatter(ad_spend,profit,
            s=profit,
            c=colors,
            cmap="Greens",
            alpha=0.8,
            edgecolor="purple",
            linewidth=1.2
            )
plt.title("advertising spend vs profit (with color and size)", fontsize=14,fontweight="bold")
plt.xlabel("ad spend($1000)",fontsize=12)
plt.ylabel("profit($1000)",fontsize=12)
plt.colorbar(label="profit value")
plt.grid(True,linestyle="--",alpha=0.2)
plt.show()

import matplotlib.pyplot as plt
scores=[
    [10,20,30,40,50,60,70,80],
    [98,87,76,65,54,43,32,21],
    [12,34,56,78,90,98,54,32],
    [21,31,41,51,61,71,81,91],
    [22,23,24,25,26,27,28,29],
]
plt.boxplot(scores,
           patch_artist=True,
            medianprops=dict(color="green",linewidth=1),
            whiskerprops=dict(color="red",linewidth=1),
            capprops=dict(color="black",linewidth=1),
            notch=True,
            vert=True,
            labels=['A','B','C','D','E'])
plt.title=("Exam score disturibution across clases")
plt.xlabel("classes")
plt.ylabel("Scores")
plt.grid(True,linestyle="--",alpha=0.7)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
data=np.array([
    [30,32,31,45,65,76,87],
    [34,23,67,89,9,76,54],
    [12,32,54,76,34,96,97],
    [76,54,34,23,56,78,90],
    [21,31,42,53,65,76,87]

])
days=["Mon","Tue","Wed","Thur","Fri","Sat","Sun"]
weeks=["week 1","week 2","week 3","week 4","week 5"]
sns.heatmap(data,
            annot=True,
            fmt=".2f",
            xticklabels=days,
            yticklabels=weeks,
            cmap="Greens",
            linewidths=0.5)
plt.gca().set_title("weekly sales data", fontsize=14,fontweight="bold")
plt.xlabel("days")
plt.ylabel("weeks")
plt.show()